project_id = "jebsbtapavndwoqyeiet"

[functions.validate-invite-key]
verify_jwt = false

[functions.log-ip]
verify_jwt = false

[functions.execute-trade]
verify_jwt = false

[functions.redeem-promocode]
verify_jwt = false